concept_threshold: 0.5
ai_cb_terms:
  - artificial intelligence
  - machine learning
  - deep learning
  - data science
genom_cb_terms:
  - genomic
  - genome
gtr_topic_search:
  - genom
  - genetic
  - artificial intelligence
gtr_genom_concepts:
  - Genomics
  - Functional genomics
  - Environmental Genomics
  - Genome organisation
gtr_ai_concepts:
  - Artificial Intelligence
gtr_ai_abstract:
  - random forest
  - " svm "
  - logistic
  - lasso
  - machine learning
  - deep learning
  - " ai "
  - " ann "
  - " gan "
  - " gnn "
  - " rnn "
  - " dnn "
  - " nlp "
  - supervised
  - unsupervised
  - reinforcement learning
  - convolutional
  - " cnn "
  - artificial intelligence
  - bayesian
  - transfer learning
  - artificial neural network
  - data science
  - data analytics
  - predictive analytics
gtr_genom_abstract:
  - genomics
  - genome
  - gwas
